version: '3.4'

services:
  sql-robo:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-robo
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=alabala.123
      - MSSQL_PID=developer 
    volumes:
      - type: volume
        source: robo-data
        target: /var/opt/mssql
  web:
    build: .
    container_name: roboweb
    ports: 
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-robo;Database=RoboDB;User Id=sa;Password=alabala.123;TrustServerCertificate=True
    depends_on:
      - sql-robo
volumes:
  robo-data: 
    driver: local