version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: "sqlRobo"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "alabala.123"
      ACCEPT_EULA: "Y"